CREATE TABLE  "Z_JP_USER" 
   (	"ID" NUMBER(5,0) NOT NULL ENABLE, 
	"FNAME" VARCHAR2(50) NOT NULL ENABLE, 
	"LNAME" VARCHAR2(50) NOT NULL ENABLE, 
	"EMAILID" VARCHAR2(50) NOT NULL ENABLE, 
	"MOBILE" VARCHAR2(14) NOT NULL ENABLE, 
	"DOB" VARCHAR2(20) NOT NULL ENABLE, 
	"PASSWORD" VARCHAR2(20) NOT NULL ENABLE, 
	 CONSTRAINT "JP_USER_ID_PK" PRIMARY KEY ("ID") ENABLE, 
	 CONSTRAINT "JP_USER_EMAILID_UNIQUE" UNIQUE ("EMAILID") ENABLE
   );
   
   
   
  CREATE TABLE  "Z_JP_MESSAGES" 
   (	"ID" NUMBER(5,0) NOT NULL ENABLE, 
	"TITLE" VARCHAR2(50) NOT NULL ENABLE, 
	"DESCRIPTION" VARCHAR2(2000) NOT NULL ENABLE, 
	"DATE_TIME" TIMESTAMP (6) DEFAULT CURRENT_TIMESTAMP, 
	 CONSTRAINT "MESSAGES_ID_PK" PRIMARY KEY ("ID") ENABLE
   );
   
   
   
 